### ISSUE TITLE
Atom selection is limited from a side view

### ISSUE THREAD

**Issue by b-zijlstra** [imc-codeteam/veevee#5]
I am not able to select atoms from every orientation. When looking at the side of the unitcell, I am unable to select most of the atoms. After rotating to a top/bottom view I am able to select them.

Probably this is a consequence of the particular implementation for determining which atom is actually being clicked on. If the fix requires significant effort I can understand if you tag this issue with `won't fix`.

**Comment by ifilot** [comment]
Actually, the problem was really easy to solve. The selection algorithm is given here http://content.gpwiki.org/index.php/OpenGL_Selection_Using_Unique_Color_IDs. Also see graphics_engine.cpp. The problem was that during the selection procedure, the atoms of the expanded unit cell were plotted as well.
